# Generated by Django 4.0.4 on 2022-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_of_published',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
